[project]
name = "artifactsmmobot"
version = "0.1.28"
description = "A telegram bot for ArtifactsMMO"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.21.0",
    "aiogram-dialog>=2.4.0",
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
]
